// JavaScript Document
/*eslint no-undef: "error"*/
/*eslint-env node*/


$(function(){
    $('#ty1').click(function(){
        $('.menu-title')
            .css({opacity:1})
        $('.menu-title2')
            .css({opacity:0})
        $('.menu-title3')
            .css({opacity:0})
        $('#ty1')
            .css({color:'white'})
            .css({backgroundColor:'black'})
        $('#ty2') 
            .css({color:'black'})
            .css({backgroundColor:'white'})   
        $('#ty3')
            .css({color:'black'})
            .css({backgroundColor:'white'})
        $('#ct1')
            .css({opacity:1})
        $('#ct2')
            .css({opacity:0})
        $('#ct3')
            .css({opacity:0})
    })

    $('#ty2').click(function(){
        $('.menu-title')
            .css({opacity:0})
        $('.menu-title2')
            .css({opacity:1})
        $('.menu-title3')
            .css({opacity:0})
        $('#ty2')
            .css({color:'white'})
            .css({backgroundColor:'black'})
        $('#ty1') 
            .css({color:'black'})
            .css({backgroundColor:'white'})   
        $('#ty3')
            .css({color:'black'})
            .css({backgroundColor:'white'})
        $('#ct2')
            .css({opacity:1})
        $('#ct1')
            .css({opacity:0})
        $('#ct3')
            .css({opacity:0})
    })

    $('#ty3').click(function(){
        $('.menu-title')
            .css({opacity:0})
        $('.menu-title2')
            .css({opacity:0})
        $('.menu-title3')
            .css({opacity:1})
        $('#ty3')
            .css({color:'white'})
            .css({backgroundColor:'black'})
        $('#ty2') 
            .css({color:'black'})
            .css({backgroundColor:'white'})   
        $('#ty1')
            .css({color:'black'})
            .css({backgroundColor:'white'})
        $('#ct3')
            .css({opacity:1})
        $('#ct2')
            .css({opacity:0})
        $('#ct1')
            .css({opacity:0})
    })
});
